[package]
name = "relay-transport-connect"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
connectrpc.workspace = true
relay-application = { path = "../relay-application" }
relay-domain = { path = "../relay-domain" }
relay-protocol = { path = "../relay-protocol" }
tokio.workspace = true
tokio-stream.workspace = true

[lints]
workspace = true
