[package]
name = "relay-testkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
relay-application = { path = "../relay-application", version = "1.0.0" }
relay-domain = { path = "../relay-domain", version = "1.0.0" }
tokio.workspace = true

[lints]
workspace = true
