[package]
name = "relay-testkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
relay-application = { path = "../relay-application" }
relay-domain = { path = "../relay-domain" }
tokio.workspace = true

[lints]
workspace = true
