[package]
name = "pocket-omp-relay-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "relay-server"
path = "src/bin/relay-server.rs"

[[bin]]
name = "relay-migrate"
path = "src/bin/relay-migrate.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
relay-adapters = { path = "../../crates/relay-adapters" }
relay-application = { path = "../../crates/relay-application" }
relay-domain = { path = "../../crates/relay-domain" }
relay-telemetry = { path = "../../crates/relay-telemetry" }
relay-transport-connect = { path = "../../crates/relay-transport-connect" }
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
